import "~/utils/styles/globals.css";

import { Theme } from "@radix-ui/themes";
import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/utils/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <Theme
            appearance="dark"
            accentColor="indigo"
            grayColor="slate"
            radius="medium"
          >
            {children}
          </Theme>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
